language: python

notifications:
    email: false

before_install:
    - rvm use 2.2.2 --install --binary
    - gem install gist
    - sudo apt-get update -qq
    - sudo apt-get -y install gdb
    - sudo cp /bin/ls ./bin/ls
    - git clone https://github.com/radare/radare2.git
    - ./radare2/sys/install.sh
    - pip install r2pipe
    - mkdir log/

script:
    - python ./src/test.py

after_script:
    - gist -a --private ./log/*
